### Request 1: CREATE first exercise Squat
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Squat",
    "reps": 10,
    "weight": 30,
    "unit": "lbs",
    "date": "01-18-22"
}

### Request 2: CREATE second exercise Clean
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Clean",
    "reps": 12,
    "weight": 25,
    "unit": "kgs",
    "date": "01-18-22"
}

### Request 3: CREATE third exercise Jerk
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Jerk",
    "reps": 12,
    "weight": 30,
    "unit": "lbs",
    "date": "01-25-22"
}

### Request 4: CREATE fourth exercise Snatch
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Snatch",
    "reps": 10,
    "weight": 30,
    "unit": "kgs",
    "date": "01-25-22"
}

### Request 5: CREATE fifth exercise Deadlift with
### MISSING NAME property to get 400 status code.
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "reps": 12,
    "weight": 25,
    "unit": "kgs",
    "date": "01-18-22"
}

### Request 6: CREATE sixth exercise Deadlift with
### MISSING REPS property to get 400 status code.
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "weight": 25,
    "unit": "kgs",
    "date": "01-18-22"
}

### Request 7: CREATE seventh exercise Deadlift with
### INVALID WEIGHT property 400 status code.
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": "12",
    "unit": "kgs",
    "date": "01-18-22"
}

### Request 8: CREATE eighth exercise Deadlift with
### INVALID UNITS property to get 400 status code.
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 12,
    "weight": 25,
    "date": "01-18-22"
}


### Request 9: CREATE the ninth exercise Deadlift with 
### INVALID DATE to get 400 status code.
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 12,
    "weight": 25,
    "unit": "kgs",
    "date": "aa-18-22"
}


### Request 10: RETRIEVE should return the 4 exercises we have created.
GET http://localhost:3000/exercises HTTP/1.1


### Request 11: CREATE fifth exercise Deadlift with
### ALL parameters
POST http://localhost:3000/exercises HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 5,
    "weight": 20,
    "unit": "lbs",
    "date": "01-22-22"
}

### Request 12: UPDATE the fifth exercise with reps at 12 and unit at kgs (weight remains 20)
### CHANGE the value of ID in the following URL 
###        to the ID assigned to Deadlift with date 01-22-22.
PUT http://localhost:3000/exercises/62ec17b8c27f3d06547b7a2b HTTP/1.1
content-type: application/json

{
    "name": "Deadlift",
    "reps": 12,
    "weight": 20,
    "unit": "kgs",
    "date": "01-22-22"
}

### Request 13: RETRIEVE for non-existent ID. 404 status code
GET  http://localhost:3000/exercises/62ec0d357984e67ef4eecd77 HTTP/1.1


### Request 14: DELETE the Deadlift with date 01-22-22.
### CHANGE the value of ID in the following URL to the ID assigned
###     to Deadlift with date 01-22-22. You can find that ID from the
##      previous retrieve request.
DELETE http://localhost:3000/exercises/62ec17b8c27f3d06547b7a2b HTTP/1.1


### Request 15: VERIFY that the Deadlift on 01-22-22 
### has been deleted, to get a 404 status code.
GET http://localhost:3000/exercises/62ec17b8c27f3d06547b7a2b HTTP/1.1


### Request 16: VERIFY that the Deadlift on 01-25-22 has been deleted.
GET http://localhost:3000/exercises HTTP/1.1


### Request 17: DELETE for non-existent ID to get a 404 status code.
DELETE http://localhost:3000/exercises/6281b322c7c796ea344f05ee HTTP/1.1